name: Lint

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run Lint Action
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          eslint_extensions: "js,jsx,ts,tsx"
          auto_fix: true
          commit: true
          git_name: "Lint Action"
          git_email: "lint-action@github.com"
          commit_message: "Fix code style issues with ESLint"
